version: "3.9"  # 指定 Docker Compose 使用的文件格式版本，3.9 是较新的稳定版本

services:
  backend:  # 定义后端服务（Django）
    build:
      context: ./backend  # 设置构建上下文为 backend 目录（寻找 Dockerfile）
      dockerfile: Dockerfile
    container_name: ctf_backend # 容器名称
    ports:  
      - "8000:8000" # 将主机的 8000 端口映射到容器的 8000 端口
    volumes:
      - ./backend:/app  # 将本地 backend 目录挂载到容器的 /app 目录，实现代码实时同步
    env_file:
      - .env  # 引入环境变量文件（.env）
    depends_on:
      - db  # 表示该服务依赖 db 服务（数据库）

  db: # 定义数据库服务
    image: postgres:15  # 使用官方 PostgreSQL 15 镜像
    container_name: ctf_postgres  # 容器名称
    restart: always # 容器失败自动重启
    environment:  # 数据库环境变量配置
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 将数据库数据持久化

volumes:
  postgres_data:  # 定义持久化数据卷，保存 PostgreSQL 数据
