# Generated by Django 5.2.4 on 2025-07-24 04:17

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "登录"),
                            ("LOGOUT", "登出"),
                            ("PASSWORD_CHANGE", "密码修改"),
                            ("2FA_ENABLED", "启用双因素认证"),
                            ("PROFILE_UPDATE", "资料更新"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="用户代理"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="操作详情"),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志管理",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="会话Key"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "user_agent",
                    models.CharField(max_length=255, verbose_name="用户代理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="最后活动"),
                ),
            ],
            options={
                "verbose_name": "用户会话",
                "verbose_name_plural": "用户会话管理",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="邮箱验证状态"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="手机验证状态"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="TOTP密钥"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="双因素认证"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后登录时间"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_5ce40b_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["phone"], name="accounts_cu_phone_c30b3c_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["create_time"], name="accounts_cu_create__87fa7d_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together={("user", "session_key")},
        ),
    ]
